DB rework
dsroklub/roprotokol pull request #27
Opened 2018-10-10 20:15 UTC by elgaard

2018-10-10 21:09 UTC, elhaard requested changes

2018-10-10 21:09 UTC, elhaard commented on db_setup/alter2018.sql
> +ALTER TABLE Boat DROP COLUMN BoatType;
Hvis du absolut skal lave den slags ændringer, kunne du godt lave de nødvdendige konsekvensrettelser også, f.x. i årsrapporterne.

Og `BoatID` i `Trip`...

2018-10-10 21:09 UTC, elhaard commented on db_setup/mkdb.sql
> +  PRIMARY KEY (`Name`)
... men betydningsbærende nøgler er en ualmindelig skidt idé.

Læs f.x. https://www.techrepublic.com/blog/10-things/10-tips-for-choosing-between-a-surrogate-and-natural-primary-key/

I det her tilfælde er det ekstra dumt: Vi genbruger bådnavne. Så man vil ikke kunne se forskel på, om en tur er roet i den gamle eller den nye båd med samme navn.

2018-10-15 23:47 UTC, elgaard commented on db_setup/alter2018.sql
> +ALTER TABLE Boat DROP COLUMN BoatType;
Det kommer

2018-11-07 18:51 UTC, merged